name: bago
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter 

  cupertino_icons: ^1.0.2
  rxdart: ^0.21.0
  http:
  flutter_plugin_pdf_viewer: ^1.0.7
  shared_preferences: ^0.5.2
  modal_progress_hud: ^0.1.3
  bubble_tab_indicator: ^0.1.4
  pull_to_refresh: ^1.5.7
  url_launcher: ^5.4.5
  connectivity: ^0.4.8+6
  webview_flutter: ^0.3.22+1
  firebase_messaging: ^6.0.16
  flushbar: ^1.10.4
  sqflite: ^1.3.1
  path_provider: ^1.1.0
  google_maps_flutter: ^0.5.28+1
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1 

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/icon_bago.png"
  adaptive_icon_background: "assets/icons/icon_bago.png"

flutter:

 
  uses-material-design: true
  assets:
    - assets/imagenes/
    - assets/gifs/
    - assets/icons/
    - assets/imagenes/imagenes_farmacorp/